title:  "Arlo O'Keeffe"
name: "Arlo O'Keeffe"
author: "Arlo O'Keeffe"
url: https://arlol.github.io
description: "Stuff done by Arlo O'Keeffe"
exclude: [Gemfile, Gemfile.lock, gravatar-favicon.sh, arlol-github-page.sublime-project, arlol-github-page.sublime-workspace]
paginate: 10
permalink: /articles/:year-:month-:day-:title.html
paginate_path: "/articles/page:num/"
language: en
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
sass:
  style: compressed
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
